export enum TypeIngredient {
  VEGETABLE = "VEGETABLE", MILK_PRODUCT = "MILK_PRODUCT", FISH = "FISH", MEAT = "MEAT", ALCOHOL = "ALCOHOL",
  FRUIT = "FRUIT", JUICE = "JUICE", NUT = "NUT", BERRY = "BERRY",
  EGG = "EGG", GRAIN_PRODUCT = "GRAIN_PRODUCT", MUSHROOMS = "MUSHROOMS", SEAFOOD = "SEAFOOD", OIL = "OIL",
  SUGAR = "SUGAR", SALT = "SALT", CANDY = "CANDY",
  CONDIMENT = "CONDIMENT", HERBAGE = "HERBAGE", DRIED_FRUITS = "DRIED_FRUITS", SAUCE = "SAUCE"
}
