ALTER TABLE favorite
    ADD CONSTRAINT FK_FAVORITE_USER_ID FOREIGN KEY (user_id) REFERENCES USER (id);

ALTER TABLE favorite
    ADD CONSTRAINT FK_FAVORITE_RECIPE_ID FOREIGN KEY (recipe_id) REFERENCES recipe (id);