ALTER TABLE category_recipe
    ADD CONSTRAINT FK_CATEGORY_RECIPE_RECIPE_ID FOREIGN KEY (recipe_id) REFERENCES RECIPE (id);

ALTER TABLE category_recipe
    ADD CONSTRAINT FK_CATEGORY_RECIPE_CATEGORY_ID FOREIGN KEY (category_id) REFERENCES CATEGORY (id);